<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerM2z0k8h\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerM2z0k8h/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerM2z0k8h.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerM2z0k8h\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerM2z0k8h\appDevDebugProjectContainer(array(
    'container.build_hash' => 'M2z0k8h',
    'container.build_id' => 'a4689b1c',
    'container.build_time' => 1534055731,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerM2z0k8h');
